### ISSUE TITLE
Compilter error due to connection refused

### ISSUE THREAD

**Issue by Rupertredding** [monax/cli#1358]
Please include in your bug report:

- [ 17.03.1-ce, build c6d412e] `docker version`
- [ 0.16.0] `eris version`
- [ go1.8 darwin/amd64] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ OS X 10.12.4] operating system details (osx/windows/linux)
- [ compile idi.sol & load] what you expected to happen
- [ Compilation fails saying connection refused. I've local Compiler service running but no way to use it] what actually happened
- [ I followed the monax 'getting started' tutorial and failing at step 3.3] steps to reproduction

============================
$ monax pkgs do --chain simplechain --address $addr -v
Using Compiler at                             https://compilers.monax.io:10160
Using Chain at                                simplechain
Using Signer at                               http://127.0.0.1:4767
Using ChainID from Node                       simplechain
Loading monax Jobs Definition File.
Service is running                            compilers

*****Executing Job*****

Job Name                                      defaultAddr
Type                                          Account
Setting Account                               669F893682766CD20E5000F24AAFCBDED8687FEE
Service is running                            keys
Service is running                            keys
Executing container                           keys-b7699e14-70d3-48e1-a8f8-b870ee7705b3
Manage data containers?              autodata=true
Data container already exists, am not creating
Executing interactive container               interactive-65bcf6b0-7bbb-430e-a8dd-5792b1f94f85
                                          cmd=[monax-keys pub --addr 669F893682766CD20E5000F24AAFCBDED8687FEE]
                               data container=keys-c7792023-5a3d-4681-8f23-44c95206b854
                                   entrypoint=[]
                                  environment=[MONAX_KEYS_HOST=172.17.0.2]
                                        image=quay.io/monax/keys:0.16.0
                              ports published=true
                                         user=root
                                         vols=[]
                                      workdir=
Waiting for container to exit                 interactive-65bcf6b0-7bbb-430e-a8dd-5792b1f94f85
Removing container                            interactive-65bcf6b0-7bbb-430e-a8dd-5792b1f94f85
Container removed                             interactive-65bcf6b0-7bbb-430e-a8dd-5792b1f94f85

*****Executing Job*****

Job Name                                      setStorageBase
Type                                          Set
Setting Variable                              5

*****Executing Job*****

Job Name                                      deployStorageK
Type                                          Deploy
Contract path                                 idi.sol
failed to send HTTP request Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
Error compiling contracts: Compilers error:
Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
======================================================
If issue is a feature request, tell us why this feature is useful.

**Comment by zramsay** [comment]
this can fixed by adding one line in `~/.monax/services/compilers.toml`;
below `[service]`, add the line:
`ports = ["9090:9090"]`

**Comment by Rupertredding** [comment]
Thanks a lot Zach!!

Now I'm hitting another issue

$ monax pkgs do --chain simplechain --address $addr -v
Using Compiler at                             https://compilers.monax.io:10160
Using Chain at                                simplechain
Using Signer at                               http://127.0.0.1:4767
Error connecting to node (tcp://127.0.0.1:46657) to get chain id: Post http://127.0.0.1:46657: EOF

**Comment by zramsay** [comment]
can you try on a linux machine?

**Comment by Rupertredding** [comment]
I don't have access to linux machine. Any plans to fix the issue on Mac?

**Comment by VoR0220** [comment]
We're moving away from multiple os' but it should be fixed up in the next version. Big things planned around compiler.

**Comment by compleatang** [comment]
@Rupertredding you can easily boot a linux virtual machine with virtualbox from a Mac. Closing this for now.

**Comment by larslue** [comment]
I can confirm that the bug still exists in the latest version of monax. (Compiler version `quay.io/monax/compilers:0.18.0`)

The bug could be fixed by adding the following line after the line `[service]` of the file `~/.monax/services/compiler.toml`:

    ports = ["9090:9090", "9099:9099"]

OS for testing was MacOS Sierra 10.12.5 (16F73).

**Comment by jppgks** [comment]
@Rupertredding Did you manage to fix that `Error connecting to node (tcp://127.0.0.1:46657) to get chain id`?

**Comment by zramsay** [comment]
@larslue and everyone else. This bug has been fixed on latest develop (#1426) and will make the next release
